SELECT
  cod_proye,
  id,
  titulo,
  descripcion,
  zip_foto,
  sitio_web,
  anio_inicio,
  anio_finalizacion,
  estado_restauracion,
  tipo_resstauracion,
  objetivo,
  actividad_plantacion,
  sistema_plantacion,
  disenio_arreglo,
  opciones_foresteria,
  tenencia,
  ods,
  documento_iniciativa,
  nombre_responsable,
  informacion_contacto,
  palabras_clave,
  tipo_org,
  pais,
  departamento,
  municipio,
  area_comprometida,
  area_total,
  unidad,
  nombre_sitio,
  planes_restauracion,
  tipologia_ecosistemas,
  actividad,
  indicadores_aurora,
  ST_AsGeoJSON(ST_Transform(geom, 4326)) AS geom
FROM pnr.ferm_query
LIMIT 50;
